OptionAssignment/OptionAssignment/OptionSelection/Controllers/AdminOptionManagementController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OptionClassLibrary.Models;
using OptionSelection.DataContext;

namespace OptionSelection.Controllers
{
    [Authorize(Roles="Admin")]
    public class AdminOptionManagementController : Controller
    {
        private OptionContext db = new OptionContext();

        public ActionResult Index()
        {
            return View(db.Options.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Title,IsActive")] Option option)
        {
            if (ModelState.IsValid)
            {
                var existingOption = db.Options.Find(option.Title);
                if(existingOption == null)
                {
                    db.Options.Add(option);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ViewBag.Error = "There is already an option with that name";
            }
            return View(option);
        }

        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Option option = db.Options.Find(id);
            if (option == null)
            {
                return HttpNotFound();
            }
            return View(option);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Title,IsActive")] Option option)
        {
            if (ModelState.IsValid)
            {
                db.Entry(option).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(option);
        }

        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Option option = db.Options.Find(id);
            if (option == null)
            {
                return HttpNotFound();
            }
            return View(option);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Option option = db.Options.Find(id);
            db.Options.Remove(option);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OptionAssignment/OptionAssignment/OptionSelection/Controllers/AdminStudentChoicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OptionClassLibrary.Models;
using OptionSelection.DataContext;
using OptionSelection.Models;

namespace OptionSelection.Controllers
{
    [Authorize(Roles="Admin")]
    public class AdminStudentChoicesController : Controller
    {
        private OptionContext db = new OptionContext();

        public SelectList DropDownListChoices { get; set; }

        public ActionResult Index()
        {
            DropDownListChoices = new SelectList(db.Terms.ToList(), "TermCode", "Description");
            ViewBag.DropDown = DropDownListChoices;
            return View(db.Choices.ToList());
        }

        [HttpPost]
        public ActionResult Search(string DropDown)
        {
            DropDownListChoices = new SelectList(db.Terms.ToList(), "TermCode", "Description");
            ViewBag.DropDown = DropDownListChoices;
            if (DropDown == "")
            {
                return View("Index", db.Choices.ToList());
            }
            int term = Convert.ToInt32(DropDown);
            return View("Index", db.Choices.Where(c => c.TermCode == term).ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OptionAssignment/OptionAssignment/OptionSelection/Controllers/AdminTermManagementController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OptionClassLibrary.Models;
using OptionSelection.DataContext;

namespace OptionSelection.Controllers
{
    [Authorize(Roles="Admin")]
    public class AdminTermManagementController : Controller
    {
        private OptionContext db = new OptionContext();

        public ActionResult Index()
        {
            return View(db.Terms.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="TermCode,Description,IsActive")] Term term)
        {
            if (ModelState.IsValid)
            {
                var existingTerm = db.Terms.Find(term.TermCode);
                if(existingTerm == null)
                {
                    db.Terms.Add(term);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ViewBag.Error = "A term with that term code already exists";
            }

            return View(term);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Term term = db.Terms.Find(id);
            if (term == null)
            {
                return HttpNotFound();
            }
            return View(term);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="TermCode,Description,IsActive")] Term term)
        {
            if (ModelState.IsValid)
            {
                if (term.IsActive)
                {
                    if (db.Terms.Where(t => t.IsActive).Count() > 0)
                    {
                        ViewBag.Error = "Only one Term can be active! You must deacivate another term.";
                        return View(term);
                    }
                }
                db.Entry(term).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(term);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Term term = db.Terms.Find(id);
            if (term == null)
            {
                return HttpNotFound();
            }
            return View(term);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Term term = db.Terms.Find(id);
            db.Terms.Remove(term);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OptionAssignment/OptionAssignment/OptionSelection/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BCIT School of Computing :: @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    <style>
        a.navbar-brand {
            background: url(../Images/logo.png) no-repeat top left;
            display: block;
            width: 150px;
            height: 150px;
            text-indent: -9999px; /* hides the link text */
        }
    </style>
</head>
<body style="background-color:grey;">
    <div class="container">
        <div class="navbar navbar-inverse navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Options Selection Form", "CreateChoice", "Home", new { area = "" }, null)</li>
                        @if (HttpContext.Current.User.IsInRole("Admin"))
                        {
                        <li>@Html.ActionLink("Options", "Index", "AdminOptionManagement", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("Terms", "Index", "AdminTermManagement", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("Users", "IndexUser", "Account", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("Roles", "IndexRole", "Account", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("Student Choices", "Index", "AdminStudentChoices", new { area = "" }, null)</li>
                        }
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>


        <div class="container body-content" style="background-color:white;">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year</p>
            </footer>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>